# This is regular daily test


name: DailyTest


on:
  schedule:
    - cron:  '8 4 * * *'
    
  workflow_dispatch:
  
        
jobs:
  pipeline:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
          
      - name: Install Depedencies
        run: |
          npm install
          npm audit fix --force
          
      - name: Run Tests
        run: |
          ./bin/runTests.sh
